apiVersion: 1

datasources:
  - name: InfluxDB-F1Tenth
    uid: influxdb-f1tenth
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: f1tenth
      defaultBucket: f1tenth_dt
      tlsSkipVerify: true
    secureJsonData:
      token: f1tenth-local-dev-token
